### ISSUE TITLE
XBEExplorer opening XBE file access violation error popup

### ISSUE THREAD

**Issue by kaosengr** [PatrickvL/Dxbx#2]
A lot of the time when trying to open an XBE file with XBEExplorer I receive the following error:

Access violation at address NNNNNNNN in module
'XBEExplorer.exe'. Read of address 00000004.

NNNNNNNN varies but is the same when trying to open the same xbe file again.

But, I can then try a different XBE file after closing the error box and it will open without a problem.  Retry the offending file and it still fails to open again showing the pop-up error message.

**Comment by kaosengr** [comment]
Closed another application, radare2, that I had the default.xbe open in that was causing the error.  Maybe a check could be made to make sure the file is not in use by another application and show a different message stating, "File already in use by another application: \<xyz\>."  I'm not sure if the value of \<xyz\> can be obtained, would be nice.

**Comment by PatrickvL** [comment]
File in use plagues Excel too, I'll see what I can do

**Comment by PatrickvL** [comment]
I've looked into this; This problem can't be avoided because the file-open-flags of all other applications that access a file *must* allow reading from other applications, so that we can open it again. (And XbeExplorer can't influence what others do.)

I did make a slight change, so that we don't forbid reading by others anymore, so if you first open an .xbe in XbeExplorer, and only then in another application, it might work.
